import { Button, LineEdit } from "std-widgets.slint";

export global GlobalData {
    in property <string> os_version: "OS";
    in property <string> host_name: "hostname";

    in property <string> eth0_mac: "nw_0_mac";
    in property <string> wlan0_mac: "nw_0_mac";

    in property <string> cpu_load: "100.0% 100.0% 100.0% 100.0%";

    in property <string> cpu_temp: "100.0 ℃";

    in property <string> memory: "1000 MB / 4000 MB";
    in property <string> swap: "1000 MB / 4000 MB";

    in property <string> dev_sda_1: "1000 GB / 4000 GB";
    in property <string> dev_sda_2: "1000 GB / 4000 GB";

    pure callback button(int);
}

global Style {
    // in property <color> TEXT_COLOR: black;
    in property <length> FONT_SIZE: 18pt;
}

export component MainWindow inherits Window {
    width: 800px;
    height: 480px;

    LineEdit {
        x: 400px;
        y: 280px;
        width: 200px;
        font-size: Style.FONT_SIZE;
        placeholder-text: "Text 1";
    }

    LineEdit {
        x: 400px;
        y: 360px;
        width: 200px;
        font-size: Style.FONT_SIZE;
        placeholder-text: "Text 2";
    }

    // Навигация
    Button {
        x: 5px;
        y: 425px;
        width: 90px;
        height: 50px;
        text: "1";
    }

    Button {
        x: 105px;
        y: 425px;
        width: 90px;
        height: 50px;
        text: "2";
    }

    Button {
        x: 205px;
        y: 425px;
        width: 90px;
        height: 50px;
        text: "";
    }

    Text {
        x: 205px;
        y: 425px;
        width: 90px;
        height: 50px;
        text: "3";
        horizontal-alignment: TextHorizontalAlignment.center;
        vertical-alignment: TextVerticalAlignment.center;
        font-size: Style.FONT_SIZE;
    }
}
