{
 "title": "tokio_metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "workers_count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM raw WHERE ($__timeFilter(\"time\") AND entity = 'tokio_runtime' AND attr = 'workers_count') ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "elapsed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM raw WHERE ($__timeFilter(\"time\") AND entity = 'tokio_runtime' AND attr = 'elapsed') ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "busy_ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'busy_ratio' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "park_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"total_park_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'total_park_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"max_park_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'max_park_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"min_park_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'min_park_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "busy_duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"total_busy_duration\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'total_busy_duration' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"max_busy_duration\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'max_busy_duration' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"min_busy_duration\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'min_busy_duration' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "steal_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"total_steal_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'total_steal_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"max_steal_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'max_steal_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"min_steal_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'min_steal_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "poll_duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"mean_poll_duration\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'mean_poll_duration' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"mean_poll_duration_worker_min\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'mean_poll_duration_worker_min' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"mean_poll_duration_worker_max\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'mean_poll_duration_worker_max' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "queue_depth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"global_queue_depth\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'global_queue_depth' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"total_local_queue_depth\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'total_local_queue_depth' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"max_local_queue_depth\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'max_local_queue_depth' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"min_local_queue_depth\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'min_local_queue_depth' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "polls_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"total_polls_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'total_polls_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"max_polls_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'max_polls_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"min_polls_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'min_polls_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "schedule_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"num_remote_schedules\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'num_remote_schedules' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"total_local_schedule_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'total_local_schedule_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"max_local_schedule_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'max_local_schedule_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"min_local_schedule_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'min_local_schedule_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "noop_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"total_noop_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'total_noop_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"max_noop_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'max_noop_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"min_noop_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'min_noop_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "steal_operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"total_steal_operations\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'total_steal_operations' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"max_steal_operations\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'max_steal_operations' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"min_steal_operations\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'min_steal_operations' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "overflow_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"total_overflow_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'total_overflow_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"max_overflow_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'max_overflow_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"min_overflow_count\" FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'min_overflow_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" "
    }
   ]
  },
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "live_tasks_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'live_tasks_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "blocking_threads_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'blocking_threads_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "idle_blocking_threads_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'idle_blocking_threads_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "budget_forced_yield_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'budget_forced_yield_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "io_driver_ready_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value FROM raw WHERE (entity = 'tokio_runtime' AND attr = 'io_driver_ready_count' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    }
   ]
  }
 ]
}